version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./api:/www
      - nodemodules:/www/node_modules
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    build:
      context: ./db
      dockerfile: ./Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  nodemodules: {}
  my-db:
